version: 2

project_name: mni

before:
  hooks:
    - go mod tidy

builds:
  - id: mni
    main: ./cmd
    binary: mni
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: mni
    ids:
      - mni
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: mni
    ids:
      - mni
    homepage: https://github.com/mNi-Cloud/cli
    description: Command line client for mNi Cloud
    directory: Formula
    install: |
      bin.install "mni"
    test: |
      system "#{bin}/mni", "--version"
    repository:
      owner: mNi-Cloud
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
